name: Build and Deploy NetDebugClient (Windows)

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/build-exe.yml'
      - 'qml/**'
      - 'User/**'
      - 'web/**'
      - 'CMakeLists.txt'

  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install aqtinstall
      run: pip install aqtinstall

    - name: Install Qt 6.9.1 (MSVC 2022 x64)
      run: cmd /c "aqt install-qt windows desktop 6.9.1 win64_msvc2022_64 --modules all --outputdir C:/Qt"

    - name: 📦 Get LibXR
      run: |
        git clone https://github.com/Jiu-xiao/libxr.git

    - name: Configure CMake project
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=C:/Qt/6.9.1/msvc2022_64 -DCMAKE_BUILD_TYPE=Release

    - name: Build project (Release)
      run: cmake --build build --config Release

    - name: Run windeployqt on built exe
      working-directory: build/Release
      run: |
        C:/Qt/6.9.1/msvc2022_64/bin/windeployqt.exe NetDebugClient.exe --qmldir ../../qml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetDebugClient-Windows
        path: build/Release/**
